In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity

In [10]:
df= pd.read_csv(r"..\assets\SpotifySongs.csv")
df.shape
df.info()
df.columns
df.describe().T

<class 'pandas.DataFrame'>
RangeIndex: 3731 entries, 0 to 3730
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SongName          3731 non-null   str
 1   ArtistName        3731 non-null   str
 2   Popularity        3731 non-null   int64
 3   Danceability      3731 non-null   float64
 4   Energy            3731 non-null   float64
 5   Key               3731 non-null   int64
 6   Loudness          3731 non-null   float64
 7   Mode              3731 non-null   int64
 8   Speechiness       3731 non-null   float64
 9   Acousticness      3731 non-null   float64
 10  Instrumentalness  3731 non-null   float64
 11  Liveness          3731 non-null   float64
 12  Valence           3731 non-null   float64
 13  Tempo             3731 non-null   float64
 14  Duration_ms       3731 non-null   int64
dtypes: float64(9), int64(4), str(2)
memory usage: 437.4 KB

,count,mean,std,min,25%,50%,75%,max
Popularity,3731.0,65.066470,23.497576,0.000000,56.00000,73.0000,81.000000,97.000
Danceability,3731.0,0.605458,0.156735,0.085800,0.51000,0.6300,0.721000,0.970
Energy,3731.0,0.586561,0.217523,0.005020,0.45300,0.6280,0.754000,0.990
Key,3731.0,4.884749,3.647925,0.000000,1.00000,5.0000,8.000000,11.000
Loudness,3731.0,-7.610220,5.043379,-34.991000,-8.42600,-6.2370,-4.884000,-1.190
Mode,3731.0,0.584294,0.492909,0.000000,0.00000,1.0000,1.000000,1.000
Speechiness,3731.0,0.084800,0.087001,0.023500,0.03615,0.0474,0.092600,0.966
Acousticness,3731.0,0.313658,0.308686,0.000032,0.04850,0.2040,0.536000,0.993
Instrumentalness,3731.0,0.076124,0.233818,0.000000,0.00000,0.0000,0.000268,0.977
Liveness,3731.0,0.166752,0.118579,0.024600,0.09720,0.1180,0.192000,0.985
Valence,3731.0,0.421331,0.226673,0.034300,0.22800,0.4220,0.603000,0.969
Tempo,3731.0,119.273201,28.668209,49.034000,95.86550,119.9760,139.941000,205.895
Duration_ms,3731.0,205163.264808,56522.919213,35240.000000,177458.00000,201254.0000,227633.500000,690732.000

In [12]:
features = [
    "Popularity",
    "Danceability",
    "Energy",
    "Key",
    "Loudness",
    "Mode",
    "Speechiness",
    "Acousticness",
    "Instrumentalness",
    "Liveness",
    "Valence",
    "Tempo",
    "Duration_ms"
]

X = df[features]

X.head()

,Popularity,Danceability,Energy,Key,Loudness,Mode,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Duration_ms
0,62,0.896,0.678,0,-2.546,0,0.0815,0.0137,0.000041,0.1100,0.604,130.024,205450
1,84,0.785,0.431,10,-8.756,0,0.0364,0.1230,0.000000,0.0887,0.236,127.085,159382
2,72,0.483,0.468,8,-7.642,1,0.0341,0.7850,0.000000,0.1520,0.319,135.864,247941
3,68,0.384,0.728,7,-6.503,0,0.0623,0.3290,0.000018,0.3290,0.311,156.396,287374
4,67,0.955,0.538,1,-8.394,1,0.0734,0.1320,0.001460,0.0704,0.837,116.977,170769

In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler() #it calculates z score z=(x−μ​)/σ
 
X_scaled = scaler.fit_transform(X)

In [15]:
X_scaled[:5]

array([[-0.13051905,  1.85395934,  0.4204214 , -1.33922821,  1.00426683,
        -1.18555675, -0.03793019, -0.97185485, -0.32543549, -0.47866738,
         0.80597696,  0.37505796,  0.00507358],
       [ 0.80587325,  1.14566485, -0.71524091,  1.40242362, -0.22721553,
        -1.18555675, -0.5563852 , -0.61772569, -0.32561086, -0.65831871,
        -0.81772169,  0.27252648, -0.81006788],
       [ 0.29511382, -0.78140664, -0.54512146,  0.85409325, -0.00630227,
         0.84348556, -0.58282526,  1.52713712, -0.32561086, -0.12442531,
        -0.45150705,  0.57879523,  0.7569225 ],
       [ 0.12486067, -1.41312875,  0.65031255,  0.57992807,  0.21956865,
        -1.18555675, -0.25864718,  0.04970896, -0.32553173,  1.36845195,
        -0.48680484,  1.29508524,  1.45466221],
       [ 0.08229739,  2.2304402 , -0.22327384, -1.06506303, -0.15542864,
         0.84348556, -0.13104517, -0.58856592, -0.31936586, -0.81266704,
         1.83402529, -0.08010646, -0.60858277]])

In [17]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix=cosine_similarity(X_scaled)

similarity_matrix.shape

(3731, 3731)

In [18]:
song_to_index = pd.Series(df.index, index=df["SongName"]).drop_duplicates()

In [21]:
song_to_index["Higher Power"]

SongName
Higher Power     108
Higher Power     112
Higher Power     155
Higher Power     255
Higher Power     586
Higher Power     605
Higher Power     629
Higher Power    1390
Higher Power    1981
Higher Power    2802
dtype: int64

In [52]:
song_index = song_to_index["Saiyaan Ji"]

similarity_scores = similarity_matrix[song_index]

similarity_scores[:10]

array([ 1.        ,  0.16305433, -0.66936181, -0.19794522,  0.63114741,
       -0.04951128,  0.48384392, -0.23946552,  0.76182813,  0.18193798])

In [53]:
list(enumerate(similarity_scores))

[(0, np.float64(0.9999999999999998)),
 (1, np.float64(0.16305433076171547)),
 (2, np.float64(-0.6693618065194038)),
 (3, np.float64(-0.19794522477292786)),
 (4, np.float64(0.6311474141558656)),
 (5, np.float64(-0.04951127765271702)),
 (6, np.float64(0.48384392028455536)),
 (7, np.float64(-0.23946551568513025)),
 (8, np.float64(0.7618281266100433)),
 (9, np.float64(0.1819379831575718)),
 (10, np.float64(0.8411571133427991)),
 (11, np.float64(-0.019045637335574565)),
 (12, np.float64(0.4870026795406652)),
 (13, np.float64(0.37784598794284296)),
 (14, np.float64(0.5364532691242092)),
 (15, np.float64(0.7405048424226688)),
 (16, np.float64(-0.1425849551820879)),
 (17, np.float64(0.08791400376857744)),
 (18, np.float64(-0.1425849551820879)),
 (19, np.float64(-0.2636151054332932)),
 (20, np.float64(-0.2636151054332932)),
 (21, np.float64(-0.516686227590801)),
 (22, np.float64(-0.5823544121152756)),
 (23, np.float64(-0.383445120784676)),
 (24, np.float64(0.14222670604196772)),
 (25, np.float64(0.14222670604196772)),
 (26, np.float64(0.48058761312312)),
 (27, np.float64(-0.6801486384141888)),
 (28, np.float64(-0.38534471024822914)),
 (29, np.float64(-0.7773847226021079)),
 (30, np.float64(-0.15984768532518234)),
 (31, np.float64(0.4143623059211286)),
 (32, np.float64(0.7171110553840505)),
 (33, np.float64(-0.4772585725311432)),
 (34, np.float64(-0.4504104097793341)),
 (35, np.float64(-0.16353534662801197)),
 (36, np.float64(0.1819379831575718)),
 (37, np.float64(0.17757388953682982)),
 (38, np.float64(-0.33261816004311523)),
 (39, np.float64(-0.038502399483436964)),
 (40, np.float64(0.4724859846988139)),
 (41, np.float64(-0.05382252109933445)),
 (42, np.float64(-0.4772585725311432)),
 (43, np.float64(-0.06236724591725051)),
 (44, np.float64(0.257093972884681)),
 (45, np.float64(0.23299843003021756)),
 (46, np.float64(0.07103460625925809)),
 (47, np.float64(-0.5312051450146276)),
 (48, np.float64(0.18508078422072433)),
 (49, np.float64(0.1149363740487649)),
 (50, np.float64(0.5820255803310099)),
 (51, np.float64(0.08024181500793967)),
 (52, np.float64(0.4722674995689695)),
 (53, np.float64(-0.3068892811921204)),
 (54, np.float64(0.08261739549247098)),
 (55, np.float64(-0.4085698928423917)),
 (56, np.float64(-0.06236724591725051)),
 (57, np.float64(-0.4085698928423917)),
 (58, np.float64(0.12024297708864075)),
 (59, np.float64(0.2988475482549802)),
 (60, np.float64(-0.06236724591725051)),
 (61, np.float64(0.29471295060163594)),
 (62, np.float64(0.31606829424841126)),
 (63, np.float64(-0.05382252109933445)),
 (64, np.float64(-0.4772585725311432)),
 (65, np.float64(0.24685921662506802)),
 (66, np.float64(-0.4772585725311432)),
 (67, np.float64(0.24685921662506802)),
 (68, np.float64(0.4500132787173138)),
 (69, np.float64(-0.13091143870483266)),
 (70, np.float64(-0.4174850364039441)),
 (71, np.float64(0.1819379831575718)),
 (72, np.float64(0.4097381697920036)),
 (73, np.float64(0.30680516398463115)),
 (74, np.float64(-0.038502399483436964)),
 (75, np.float64(0.14332587492971038)),
 (76, np.float64(0.12024297708864075)),
 (77, np.float64(0.14332587492971038)),
 (78, np.float64(-0.4772585725311432)),
 (79, np.float64(-0.123134096760586)),
 (80, np.float64(-0.07961113261652253)),
 (81, np.float64(-0.39950673503166795)),
 (82, np.float64(0.07835467890095116)),
 (83, np.float64(-0.5827733015325562)),
 (84, np.float64(-0.30884906077324764)),
 (85, np.float64(-0.7018035106907866)),
 (86, np.float64(-0.4085698928423917)),
 (87, np.float64(-0.4174850364039441)),
 (88, np.float64(-0.4174850364039441)),
 (89, np.float64(-0.25486830898888674)),
 (90, np.float64(-0.5142750560339375)),
 (91, np.float64(-0.5265181331130327)),
 (92, np.float64(-0.536857439986998)),
 (93, np.float64(-0.48134165568595694)),
 (94, np.float64(-0.5649078371323721)),
 (95, np.float64(-0.06236724591725051)),
 (96, np.float64(0.257093972884681)),
 (97, np.float64(0.5820255803310099)),
 (98, np.float64(0.23299843003021756)),
 (99, np.float64(0.07103460625925809)),
 (100, np.float64(-0.4772585725311432)),
 (101, np.float64(-0.6383116060681163)),
 (102, np.float64(-0.4772585725311432)),
 (103, np.float64(-0.4772585725311432)),
 (104, np.float64(0.2058893630157591)),
 (105, np.float64(-0.08763772149453528)),
 (106, np.float64(0.7408240017442893)),
 (107, np.float64(0.7408240017442893)),
 (108, np.float64(0.2058893630157591)),
 (109, np.float64(-0.08763772149453528)),
 (110, np.float64(-0.2925604381229257)),
 (111, np.float64(-0.1733758572820356)),
 (112, np.float64(-0.4772585725311432)),
 (113, np.float64(-0.3293134458641175)),
 (114, np.float64(0.16500367989519482)),
 (115, np.float64(-0.5575916307577158)),
 (116, np.float64(0.3794840092828368)),
 (117, np.float64(0.2864679523177832)),
 (118, np.float64(0.2662791686365862)),
 (119, np.float64(0.04745086230304576)),
 (120, np.float64(-0.4073114685039387)),
 (121, np.float64(-0.40113572094114525)),
 (122, np.float64(0.19491065941893757)),
 (123, np.float64(-0.1114908002914124)),
 (124, np.float64(-0.4174850364039441)),
 (125, np.float64(-0.4174850364039441)),
 (126, np.float64(-0.4174850364039441)),
 (127, np.float64(-0.4174850364039441)),
 (128, np.float64(-0.42082386458178805)),
 (129, np.float64(-0.5750450667698541)),
 (130, np.float64(-0.5750450667698541)),
 (131, np.float64(-0.5750450667698541)),
 (132, np.float64(-0.5750450667698541)),
 (133, np.float64(-0.5750450667698541)),
 (134, np.float64(-0.5750450667698541)),
 (135, np.float64(-0.5750450667698541)),
 (136, np.float64(-0.5750450667698541)),
 (137, np.float64(-0.5750450667698541)),
 (138, np.float64(-0.5750450667698541)),
 (139, np.float64(0.2662791686365862)),
 (140, np.float64(0.11689737108515752)),
 (141, np.float64(0.2104667224874922)),
 (142, np.float64(-0.3286481502686668)),
 (143, np.float64(-0.4085698928423917)),
 (144, np.float64(-0.4085698928423917)),
 (145, np.float64(-0.4085698928423917)),
 (146, np.float64(-0.4085698928423917)),
 (147, np.float64(-0.4085698928423917)),
 (148, np.float64(-0.4085698928423917)),
 (149, np.float64(-0.4085698928423917)),
 (150, np.float64(0.7408240017442893)),
 (151, np.float64(0.2058893630157591)),
 (152, np.float64(-0.08763772149453528)),
 (153, np.float64(-0.2925604381229257)),
 (154, np.float64(-0.1733758572820356)),
 (155, np.float64(0.35781507865379375)),
 (156, np.float64(0.4031251663514535)),
 (157, np.float64(-0.4141896726656212)),
 (158, np.float64(0.2662791686365862)),
 (159, np.float64(-0.1804399382424733)),
 (160, np.float64(0.5551888381085528)),
 (161, np.float64(0.13438113163128956)),
 (162, np.float64(-0.4772585725311432)),
 (163, np.float64(-0.4772585725311432)),
 (164, np.float64(-0.6141105752699079)),
 (165, np.float64(0.06679379717054709)),
 (166, np.float64(0.06679379717054709)),
 (167, np.float64(0.1997584927795784)),
 (168, np.float64(-0.4772585725311432)),
 (169, np.float64(-0.4772585725311432)),
 (170, np.float64(0.342395873915575)),
 (171, np.float64(0.342395873915575)),
 (172, np.float64(0.5958540840805898)),
 (173, np.float64(-0.36279828668260256)),
 (174, np.float64(-0.1731460585775466)),
 (175, np.float64(0.45222768453819023)),
 (176, np.float64(0.33458921544614223)),
 (177, np.float64(-0.12347425633933559)),
 (178, np.float64(0.14298007820953865)),
 (179, np.float64(0.22487294114307743)),
 (180, np.float64(0.40219571374550783)),
 (181, np.float64(0.14827897623020647)),
 (182, np.float64(0.286336381516931)),
 (183, np.float64(0.48058761312312)),
 (184, np.float64(0.17515012257465948)),
 (185, np.float64(0.2304254222817913)),
 (186, np.float64(0.23227984395882847)),
 (187, np.float64(-0.06140974702038835)),
 (188, np.float64(-0.4085698928423917)),
 (189, np.float64(-0.25486830898888674)),
 (190, np.float64(-0.5142750560339375)),
 (191, np.float64(0.1997584927795784)),
 (192, np.float64(-0.123134096760586)),
 (193, np.float64(-0.13736372117179316)),
 (194, np.float64(0.007824790300641295)),
 (195, np.float64(-0.5142750560339375)),
 (196, np.float64(-0.25486830898888674)),
 (197, np.float64(-0.5142750560339375)),
 (198, np.float64(-0.5265181331130327)),
 (199, np.float64(-0.536857439986998)),
 (200, np.float64(-0.48134165568595694)),
 (201, np.float64(-0.5649078371323721)),
 (202, np.float64(-0.510292005119406)),
 (203, np.float64(-0.4772585725311432)),
 (204, np.float64(-0.4772585725311432)),
 (205, np.float64(0.21356781344175785)),
 (206, np.float64(0.29652010875120366)),
 (207, np.float64(0.2988475482549802)),
 (208, np.float64(-0.06236724591725051)),
 (209, np.float64(-0.06910149832762351)),
 (210, np.float64(0.3621606267025986)),
 (211, np.float64(0.12024297708864075)),
 (212, np.float64(0.31606829424841126)),
 (213, np.float64(0.12024297708864075)),
 (214, np.float64(0.15410586124483305)),
 (215, np.float64(0.3621606267025986)),
 (216, np.float64(0.29471295060163594)),
 (217, np.float64(-0.2394975825583906)),
 (218, np.float64(0.2304254222817913)),
 (219, np.float64(0.23227984395882847)),
 (220, np.float64(-0.06140974702038835)),
 (221, np.float64(0.6399620185733362)),
 (222, np.float64(-0.03603248897395639)),
 (223, np.float64(0.019600922944266384)),
 (224, np.float64(-0.4085698928423917)),
 (225, np.float64(-0.4085698928423917)),
 (226, np.float64(-0.4085698928423917)),
 (227, np.float64(-0.4637461633464747)),
 (228, np.float64(-0.28135909764262734)),
 (229, np.float64(0.3621606267025986)),
 (230, np.float64(0.19360040987310384)),
 (231, np.float64(0.257093972884681)),
 (232, np.float64(0.5820255803310099)),
 (233, np.float64(0.39540957511479824)),
 (234, np.float64(-0.06910149832762351)),
 (235, np.float64(0.4503753283506347)),
 (236, np.float64(-0.2165494529116228)),
 (237, np.float64(0.7934397266208565)),
 (238, np.float64(-0.11913292829539102)),
 (239, np.float64(0.19138883619676922)),
 (240, np.float64(-0.1672308602208474)),
 (241, np.float64(0.15324852715216342)),
 (242, np.float64(0.27693312098571027)),
 (243, np.float64(-0.4772585725311432)),
 (244, np.float64(0.48384392028455536)),
 (245, np.float64(0.45027484175017646)),
 (246, np.float64(0.31444617656881757)),
 (247, np.float64(0.39662113865154003)),
 (248, np.float64(0.19589468096429624)),
 (249, np.float64(0.7408240017442893)),
 (250, np.float64(0.2058893630157591)),
 (251, np.float64(-0.08763772149453528)),
 (252, np.float64(-0.1733758572820356)),
 (253, np.float64(0.257093972884681)),
 (254, np.float64(0.29652010875120366)),
 (255, np.float64(0.2988475482549802)),
 (256, np.float64(-0.06236724591725051)),
 (257, np.float64(0.3621606267025986)),
 (258, np.float64(0.12024297708864075)),
 (259, np.float64(0.31606829424841126)),
 (260, np.float64(0.46987603474575007)),
 (261, np.float64(0.8411571133427991)),
 (262, np.float64(0.13430216558844613)),
 (263, np.float64(-0.05382252109933445)),
 (264, np.float64(0.14298007820953865)),
 (265, np.float64(-0.2636151054332932)),
 (266, np.float64(-0.22833926930378787)),
 (267, np.float64(0.1765318330031913)),
 (268, np.float64(0.16212105670289279)),
 (269, np.float64(0.1765318330031913)),
 (270, np.float64(0.1765318330031913)),
 (271, np.float64(-0.4772585725311432)),
 (272, np.float64(-0.4772585725311432)),
 (273, np.float64(0.45619213727789315)),
 (274, np.float64(-0.4174850364039441)),
 (275, np.float64(-0.4174850364039441)),
 (276, np.float64(-0.07961113261652253)),
 (277, np.float64(0.06959124391494237)),
 (278, np.float64(0.12024297708864075)),
 (279, np.float64(-0.6136764064179632)),
 (280, np.float64(0.18594753373264053)),
 (281, np.float64(-0.18452823604306912)),
 (282, np.float64(0.2636487580548576)),
 (283, np.float64(0.29949440115700643)),
 (284, np.float64(0.027019985251236837)),
 (285, np.float64(0.3832969345222784)),
 (286, np.float64(0.10307018675773864)),
 (287, np.float64(-0.1198554699916192)),
 (288, np.float64(-0.6020008794027454)),
 (289, np.float64(0.13438113163128956)),
 (290, np.float64(0.31606829424841126)),
 (291, np.float64(0.2988475482549802)),
 (292, np.float64(-0.1733758572820356)),
 (293, np.float64(0.38335918891821513)),
 (294, np.float64(0.6399620185733362)),
 (295, np.float64(0.4503753283506347)),
 (296, np.float64(0.2662791686365862)),
 (297, np.float64(0.2662791686365862)),
 (298, np.float64(-0.06910149832762351)),
 (299, np.float64(0.7934397266208565)),
 (300, np.float64(0.5820255803310099)),
 (301, np.float64(0.2530849218798371)),
 (302, np.float64(0.45619213727789315)),
 (303, np.float64(-0.7018035106907866)),
 (304, np.float64(0.3483584120709055)),
 (305, np.float64(0.47303569687510205)),
 (306, np.float64(-0.2154525810278945)),
 (307, np.float64(0.2895773600535181)),
 (308, np.float64(-0.25972974789597)),
 (309, np.float64(-0.10165491777033066)),
 (310, np.float64(0.13438113163128956)),
 (311, np.float64(-0.1733758572820356)),
 (312, np.float64(0.31606829424841126)),
 (313, np.float64(0.6399620185733362)),
 (314, np.float64(0.6399620185733362)),
 (315, np.float64(-0.06910149832762351)),
 (316, np.float64(0.5820255803310099)),
 (317, np.float64(0.2988475482549802)),
 (318, np.float64(0.2988475482549802)),
 (319, np.float64(0.4503753283506347)),
 (320, np.float64(0.2662791686365862)),
 (321, np.float64(0.38335918891821513)),
 (322, np.float64(0.7934397266208565)),
 (323, np.float64(0.2530849218798371)),
 (324, np.float64(-0.4772585725311432)),
 (325, np.float64(-0.4772585725311432)),
 (326, np.float64(0.2636487580548576)),
 (327, np.float64(0.12024297708864075)),
 (328, np.float64(0.08024181500793967)),
 (329, np.float64(0.257093972884681)),
 (330, np.float64(0.5551888381085528)),
 (331, np.float64(-0.3068892811921204)),
 (332, np.float64(-0.123134096760586)),
 (333, np.float64(-0.39950673503166795)),
 (334, np.float64(0.2530849218798371)),
 (335, np.float64(0.2636487580548576)),
 (336, np.float64(0.1765318330031913)),
 (337, np.float64(0.1765318330031913)),
 (338, np.float64(0.257093972884681)),
 (339, np.float64(0.5551888381085528)),
 (340, np.float64(-0.07961113261652253)),
 (341, np.float64(-0.4085698928423917)),
 (342, np.float64(-0.4085698928423917)),
 (343, np.float64(0.3275740602735969)),
 (344, np.float64(-0.570618281184383)),
 (345, np.float64(0.40219571374550783)),
 (346, np.float64(0.14827897623020647)),
 (347, np.float64(0.286336381516931)),
 (348, np.float64(0.45491758988214837)),
 (349, np.float64(0.07103460625925809)),
 (350, np.float64(-0.5312051450146276)),
 (351, np.float64(0.3621606267025986)),
 (352, np.float64(-0.020364644132154736)),
 (353, np.float64(-0.39950673503166795)),
 (354, np.float64(0.5958540840805898)),
 (355, np.float64(0.09475487547268757)),
 (356, np.float64(0.1765318330031913)),
 (357, np.float64(0.10895019712323947)),
 (358, np.float64(0.1819379831575718)),
 (359, np.float64(0.13975959034326943)),
 (360, np.float64(0.06679379717054709)),
 (361, np.float64(0.342395873915575)),
 (362, np.float64(0.1149363740487649)),
 (363, np.float64(-0.3068892811921204)),
 (364, np.float64(0.23299843003021756)),
 (365, np.float64(0.08261739549247098)),
 (366, np.float64(0.2866850055095186)),
 (367, np.float64(0.08024181500793967)),
 (368, np.float64(0.1765318330031913)),
 (369, np.float64(-0.15984768532518234)),
 (370, np.float64(0.13438113163128956)),
 (371, np.float64(0.45222768453819023)),
 (372, np.float64(0.06679379717054709)),
 (373, np.float64(0.1819379831575718)),
 (374, np.float64(0.342395873915575)),
 (375, np.float64(0.1866319208422628)),
 (376, np.float64(0.43222868174814716)),
 (377, np.float64(0.0051240659053221425)),
 (378, np.float64(0.01572585729314228)),
 (379, np.float64(0.4097381697920036)),
 (380, np.float64(0.5958540840805898)),
 (381, np.float64(0.1819379831575718)),
 (382, np.float64(0.1765318330031913)),
 (383, np.float64(0.06679379717054709)),
 (384, np.float64(0.342395873915575)),
 (385, np.float64(0.07103460625925809)),
 (386, np.float64(0.40219571374550783)),
 (387, np.float64(0.13438113163128956)),
 (388, np.float64(-0.15984768532518234)),
 (389, np.float64(0.18508078422072433)),
 (390, np.float64(0.5958540840805898)),
 (391, np.float64(0.1765318330031913)),
 (392, np.float64(0.1819379831575718)),
 (393, np.float64(0.06679379717054709)),
 (394, np.float64(0.342395873915575)),
 (395, np.float64(0.40219571374550783)),
 (396, np.float64(0.08024181500793967)),
 (397, np.float64(-0.40113572094114525)),
 (398, np.float64(0.11689737108515752)),
 (399, np.float64(0.5551888381085528)),
 (400, np.float64(-0.06236724591725051)),
 (401, np.float64(0.21356781344175785)),
 (402, np.float64(0.07835467890095116)),
 (403, np.float64(0.027019985251236837)),
 (404, np.float64(-0.3286481502686668)),
 (405, np.float64(0.14298007820953865)),
 (406, np.float64(0.4722674995689695)),
 (407, np.float64(0.37784598794284296)),
 (408, np.float64(-0.019045637335574565)),
 (409, np.float64(0.6652979293894317)),
 (410, np.float64(-0.4772585725311432)),
 (411, np.float64(-0.4772585725311432)),
 (412, np.float64(-0.5761633500007393)),
 (413, np.float64(-0.5761633500007393)),
 (414, np.float64(-0.5761633500007393)),
 (415, np.float64(0.4354792163352162)),
 (416, np.float64(0.4354792163352162)),
 (417, np.float64(0.03531931935167258)),
 (418, np.float64(0.03537598975461444)),
 (419, np.float64(-0.19975718827555403)),
 (420, np.float64(0.2636487580548576)),
 (421, np.float64(-0.18452823604306912)),
 (422, np.float64(0.17553366006699167)),
 (423, np.float64(0.13434130778849154)),
 (424, np.float64(0.12430072977803948)),
 (425, np.float64(0.19043578292408664)),
 (426, np.float64(0.06126776331127896)),
 (427, np.float64(0.30969310759613355)),
 (428, np.float64(-0.509130351549863)),
 (429, np.float64(-0.023324142843694835)),
 (430, np.float64(0.19043578292408664)),
 (431, np.float64(0.4201818194348496)),
 (432, np.float64(-0.2802564522229332)),
 (433, np.float64(0.3621606267025986)),
 (434, np.float64(0.5661377159521145)),
 (435, np.float64(0.3101761280900551)),
 (436, np.float64(-0.06236724591725051)),
 (437, np.float64(-0.2394975825583906)),
 (438, np.float64(-0.1266954409315538)),
 (439, np.float64(0.25117937783725097)),
 (440, np.float64(0.29652010875120366)),
 (441, np.float64(0.19043578292408664)),
 (442, np.float64(0.13760755844741765)),
 (443, np.float64(0.1149363740487649)),
 (444, np.float64(0.4201818194348496)),
 (445, np.float64(0.03531931935167258)),
 (446, np.float64(0.19752863529201187)),
 (447, np.float64(0.6768848628412355)),
 (448, np.float64(-0.06945184567665305)),
 (449, np.float64(0.03625239439583923)),
 (450, np.float64(0.4532035309951468)),
 (451, np.float64(-0.19975718827555403)),
 (452, np.float64(0.4899771719934112)),
 (453, np.float64(0.826213187940172)),
 (454, np.float64(-0.509130351549863)),
 (455, np.float64(-0.48353262792873164)),
 (456, np.float64(0.4532035309951468)),
 (457, np.float64(-0.48353262792873164)),
 (458, np.float64(0.014867185996912648)),
 (459, np.float64(0.4652041309307094)),
 (460, np.float64(-0.19975718827555403)),
 (461, np.float64(0.4899771719934112)),
 (462, np.float64(6.649883580202146e-05)),
 (463, np.float64(-0.3405144041790065)),
 (464, np.float64(0.8426418374437178)),
 (465, np.float64(0.2304254222817913)),
 (466, np.float64(-0.13736372117179316)),
 (467, np.float64(0.03537598975461444)),
 (468, np.float64(-0.15910835457938585)),
 (469, np.float64(-0.123134096760586)),
 (470, np.float64(0.23227984395882847)),
 (471, np.float64(-0.1785343222924326)),
 (472, np.float64(-0.06945184567665305)),
 (473, np.float64(0.4532035309951468)),
 (474, np.float64(0.5315923790042426)),
 (475, np.float64(0.2530849218798371)),
 (476, np.float64(-0.25486830898888674)),
 (477, np.float64(-0.5142750560339375)),
 (478, np.float64(-0.5265181331130327)),
 (479, np.float64(-0.536857439986998)),
 (480, np.float64(-0.48134165568595694)),
 (481, np.float64(-0.5649078371323721)),
 (482, np.float64(-0.510292005119406)),
 (483, np.float64(-0.5819347610408565)),
 (484, np.float64(-0.5190878002207515)),
 (485, np.float64(-0.3708100839559819)),
 (486, np.float64(-0.3762680109348326)),
 (487, np.float64(-0.4728962037627142)),
 (488, np.float64(-0.5308514291637075)),
 (489, np.float64(-0.5683751816772128)),
 (490, np.float64(-0.46484063470365233)),
 (491, np.float64(-0.5144526069378424)),

In [54]:
sorted_scores = sorted(
    list(enumerate(similarity_scores)),
    key=lambda x: x[1],
    reverse=True
)

In [31]:
top_recommendations = sorted_scores[1:6]
sorted_scores

[(0, np.float64(0.9999999999999998)),
 (2492, np.float64(0.847277327633418)),
 (2583, np.float64(0.847277327633418)),
 (2728, np.float64(0.847277327633418)),
 (2807, np.float64(0.847277327633418)),
 (2872, np.float64(0.847277327633418)),
 (3268, np.float64(0.847277327633418)),
 (464, np.float64(0.8426418374437178)),
 (970, np.float64(0.8426418374437178)),
 (1253, np.float64(0.8426418374437178)),
 (1571, np.float64(0.8426418374437178)),
 (1773, np.float64(0.8426418374437178)),
 (1781, np.float64(0.8426418374437178)),
 (1946, np.float64(0.8426418374437178)),
 (2633, np.float64(0.8426418374437178)),
 (2634, np.float64(0.8426418374437178)),
 (3035, np.float64(0.8426418374437178)),
 (10, np.float64(0.8411571133427991)),
 (261, np.float64(0.8411571133427991)),
 (1692, np.float64(0.8411571133427991)),
 (1004, np.float64(0.8403732973108331)),
 (3075, np.float64(0.8403732973108331)),
 (453, np.float64(0.826213187940172)),
 (626, np.float64(0.826213187940172)),
 (668, np.float64(0.826213187940172)),
 (904, np.float64(0.826213187940172)),
 (1223, np.float64(0.826213187940172)),
 (1239, np.float64(0.826213187940172)),
 (1413, np.float64(0.826213187940172)),
 (2509, np.float64(0.826213187940172)),
 (2611, np.float64(0.826213187940172)),
 (1184, np.float64(0.816002715756145)),
 (3695, np.float64(0.816002715756145)),
 (237, np.float64(0.7934397266208565)),
 (299, np.float64(0.7934397266208565)),
 (322, np.float64(0.7934397266208565)),
 (561, np.float64(0.7934397266208565)),
 (1955, np.float64(0.7934397266208565)),
 (2667, np.float64(0.7934397266208565)),
 (2711, np.float64(0.7934397266208565)),
 (2272, np.float64(0.7811439699631545)),
 (3182, np.float64(0.7726132039937373)),
 (3189, np.float64(0.7701006885183718)),
 (2339, np.float64(0.7690873161151013)),
 (1252, np.float64(0.763104367974588)),
 (1832, np.float64(0.763104367974588)),
 (1042, np.float64(0.762044200263173)),
 (8, np.float64(0.7618281266100433)),
 (599, np.float64(0.7618281266100433)),
 (1108, np.float64(0.7618281266100433)),
 (2405, np.float64(0.7581147009287987)),
 (853, np.float64(0.749918172025664)),
 (873, np.float64(0.749918172025664)),
 (896, np.float64(0.749918172025664)),
 (1121, np.float64(0.749918172025664)),
 (2805, np.float64(0.7486738283211494)),
 (106, np.float64(0.7408240017442893)),
 (107, np.float64(0.7408240017442893)),
 (150, np.float64(0.7408240017442893)),
 (249, np.float64(0.7408240017442893)),
 (609, np.float64(0.7408240017442893)),
 (785, np.float64(0.7408240017442893)),
 (880, np.float64(0.7408240017442893)),
 (959, np.float64(0.7408240017442893)),
 (968, np.float64(0.7408240017442893)),
 (1324, np.float64(0.7408240017442893)),
 (1330, np.float64(0.7408240017442893)),
 (1417, np.float64(0.7408240017442893)),
 (1652, np.float64(0.7408240017442893)),
 (1881, np.float64(0.7408240017442893)),
 (2003, np.float64(0.7408240017442893)),
 (2260, np.float64(0.7408240017442893)),
 (2293, np.float64(0.7408240017442893)),
 (15, np.float64(0.7405048424226688)),
 (3115, np.float64(0.7264458916803116)),
 (638, np.float64(0.7239584632501932)),
 (1555, np.float64(0.7191923137920985)),
 (1047, np.float64(0.7185488112374069)),
 (1362, np.float64(0.7185488112374069)),
 (1943, np.float64(0.7185488112374069)),
 (2641, np.float64(0.7185488112374069)),
 (32, np.float64(0.7171110553840505)),
 (1084, np.float64(0.7171110553840505)),
 (1085, np.float64(0.7171110553840505)),
 (1857, np.float64(0.7171110553840505)),
 (2625, np.float64(0.7171110553840505)),
 (1387, np.float64(0.7089828644204119)),
 (2407, np.float64(0.7035653019434099)),
 (2553, np.float64(0.6932608327927946)),
 (1990, np.float64(0.6931886282167079)),
 (2880, np.float64(0.6931886282167079)),
 (2401, np.float64(0.6839505045824589)),
 (447, np.float64(0.6768848628412355)),
 (901, np.float64(0.6768848628412355)),
 (1717, np.float64(0.6768848628412355)),
 (1718, np.float64(0.6768848628412355)),
 (1919, np.float64(0.6768848628412355)),
 (2504, np.float64(0.6768848628412355)),
 (2997, np.float64(0.6768848628412355)),
 (2999, np.float64(0.6768848628412355)),
 (3000, np.float64(0.6768848628412355)),
 (2358, np.float64(0.6735642012451432)),
 (2359, np.float64(0.6735642012451432)),
 (2377, np.float64(0.6735642012451432)),
 (2415, np.float64(0.6735642012451432)),
 (2603, np.float64(0.6735642012451432)),
 (2722, np.float64(0.6735642012451432)),
 (3013, np.float64(0.6735642012451432)),
 (3100, np.float64(0.6735642012451432)),
 (3583, np.float64(0.6735642012451432)),
 (650, np.float64(0.669228034863648)),
 (1165, np.float64(0.669228034863648)),
 (1175, np.float64(0.669228034863648)),
 (1181, np.float64(0.669228034863648)),
 (1233, np.float64(0.669228034863648)),
 (1405, np.float64(0.669228034863648)),
 (1604, np.float64(0.669228034863648)),
 (1779, np.float64(0.669228034863648)),
 (1893, np.float64(0.669228034863648)),
 (2530, np.float64(0.669228034863648)),
 (3223, np.float64(0.669228034863648)),
 (834, np.float64(0.6683072979093893)),
 (911, np.float64(0.6683072979093893)),
 (2623, np.float64(0.6683072979093893)),
 (1798, np.float64(0.6678382380282238)),
 (409, np.float64(0.6652979293894317)),
 (1474, np.float64(0.6629209832019051)),
 (1593, np.float64(0.6552582912735053)),
 (3346, np.float64(0.6543361650264699)),
 (2331, np.float64(0.6460302936552402)),
 (2348, np.float64(0.6460302936552402)),
 (2505, np.float64(0.6460302936552402)),
 (3015, np.float64(0.6460302936552402)),
 (3158, np.float64(0.6454462614193488)),
 (879, np.float64(0.6432265090897958)),
 (1331, np.float64(0.6432265090897958)),
 (1494, np.float64(0.6425439902913448)),
 (1495, np.float64(0.6425439902913448)),
 (2669, np.float64(0.6425439902913448)),
 (2710, np.float64(0.6425439902913448)),
 (2747, np.float64(0.6425439902913448)),
 (3033, np.float64(0.6425439902913448)),
 (3663, np.float64(0.6425439902913448)),
 (221, np.float64(0.6399620185733362)),
 (294, np.float64(0.6399620185733362)),
 (313, np.float64(0.6399620185733362)),
 (314, np.float64(0.6399620185733362)),
 (731, np.float64(0.6399620185733362)),
 (1299, np.float64(0.6399620185733362)),
 (1517, np.float64(0.6399620185733362)),
 (1518, np.float64(0.6399620185733362)),
 (1530, np.float64(0.6399620185733362)),
 (2352, np.float64(0.6396567479982804)),
 (1651, np.float64(0.6391136360702195)),
 (1862, np.float64(0.6361403702329006)),
 (2599, np.float64(0.6318638304393127)),
 (2723, np.float64(0.6318638304393127)),
 (4, np.float64(0.6311474141558656)),
 (3184, np.float64(0.6307227138964923)),
 (3197, np.float64(0.6306528688864024)),
 (2562, np.float64(0.6300998577986523)),
 (2055, np.float64(0.6298876079747735)),
 (2056, np.float64(0.6298876079747735)),
 (2075, np.float64(0.6298876079747735)),
 (1858, np.float64(0.6214039988733803)),
 (2404, np.float64(0.6169320808692161)),
 (2876, np.float64(0.6143702541872637)),
 (1218, np.float64(0.6131059157719817)),
 (1221, np.float64(0.6131059157719817)),
 (3334, np.float64(0.6131059157719817)),
 (2276, np.float64(0.6109373972229046)),
 (3406, np.float64(0.6040206576402337)),
 (559, np.float64(0.601829077884517)),
 (1452, np.float64(0.601829077884517)),
 (1646, np.float64(0.601829077884517)),
 (1860, np.float64(0.601829077884517)),
 (1356, np.float64(0.6007479398067553)),
 (1614, np.float64(0.6007479398067553)),
 (2106, np.float64(0.6007479398067553)),
 (1840, np.float64(0.5999291207218241)),
 (3097, np.float64(0.5999291207218241)),
 (925, np.float64(0.599750494357258)),
 (1268, np.float64(0.599750494357258)),
 (1865, np.float64(0.599750494357258)),
 (3687, np.float64(0.5971589048927318)),
 (172, np.float64(0.5958540840805898)),
 (354, np.float64(0.5958540840805898)),
 (380, np.float64(0.5958540840805898)),
 (390, np.float64(0.5958540840805898)),
 (820, np.float64(0.5958540840805898)),
 (929, np.float64(0.5958540840805898)),
 (1564, np.float64(0.5958540840805898)),
 (1680, np.float64(0.5958540840805898)),
 (2077, np.float64(0.5958540840805898)),
 (2078, np.float64(0.5958540840805898)),
 (2116, np.float64(0.5958540840805898)),
 (2306, np.float64(0.5958540840805898)),
 (2307, np.float64(0.5958540840805898)),
 (2587, np.float64(0.5958540840805898)),
 (2726, np.float64(0.5958540840805898)),
 (2754, np.float64(0.5958540840805898)),
 (2973, np.float64(0.5958540840805898)),
 (3056, np.float64(0.5958540840805898)),
 (3124, np.float64(0.5958540840805898)),
 (3143, np.float64(0.5958540840805898)),
 (3167, np.float64(0.5958540840805898)),
 (3212, np.float64(0.5958540840805898)),
 (3229, np.float64(0.5958540840805898)),
 (3272, np.float64(0.5958540840805898)),
 (3307, np.float64(0.5958540840805898)),
 (3428, np.float64(0.5958540840805898)),
 (3675, np.float64(0.5958540840805898)),
 (3150, np.float64(0.5944710894170556)),
 (941, np.float64(0.5922461072156903)),
 (2696, np.float64(0.5922461072156903)),
 (3060, np.float64(0.5922461072156903)),
 (830, np.float64(0.592107241943403)),
 (3603, np.float64(0.5912146049083967)),
 (2481, np.float64(0.5893897261718191)),
 (2564, np.float64(0.5893897261718191)),
 (2565, np.float64(0.5893897261718191)),
 (2568, np.float64(0.5893897261718191)),
 (2851, np.float64(0.5893897261718191)),
 (3700, np.float64(0.5893897261718191)),
 (1314, np.float64(0.5893635916369389)),
 (1435, np.float64(0.5893635916369389)),
 (2251, np.float64(0.5893635916369389)),
 (2952, np.float64(0.5871551170061652)),
 (2118, np.float64(0.5863334907899019)),
 (2128, np.float64(0.5863334907899019)),
 (2808, np.float64(0.5863334907899019)),
 (3584, np.float64(0.5863334907899019)),
 (1011, np.float64(0.586023148363297)),
 (621, np.float64(0.5850548886417841)),
 (663, np.float64(0.5850548886417841)),
 (801, np.float64(0.5850548886417841)),
 (1226, np.float64(0.5850548886417841)),
 (1242, np.float64(0.5850548886417841)),
 (1851, np.float64(0.5850548886417841)),
 (1855, np.float64(0.5850548886417841)),
 (1917, np.float64(0.5850548886417841)),
 (1586, np.float64(0.583184772311251)),
 (50, np.float64(0.5820255803310099)),
 (97, np.float64(0.5820255803310099)),
 (232, np.float64(0.5820255803310099)),
 (300, np.float64(0.5820255803310099)),
 (316, np.float64(0.5820255803310099)),
 (730, np.float64(0.5820255803310099)),
 (1298, np.float64(0.5820255803310099)),
 (1506, np.float64(0.5820255803310099)),
 (2387, np.float64(0.5820255803310099)),
 (2424, np.float64(0.5820255803310099)),
 (1379, np.float64(0.5820180298619073)),
 (1380, np.float64(0.5820180298619073)),
 (2601, np.float64(0.5775859254169747)),
 (1272, np.float64(0.5751184171533215)),
 (2303, np.float64(0.5726379714584766)),
 (2705, np.float64(0.5726379714584766)),
 (2036, np.float64(0.5713504684689275)),
 (2888, np.float64(0.5713504684689275)),
 (3205, np.float64(0.5713401554877204)),
 (2196, np.float64(0.5689107860051564)),
 (3238, np.float64(0.5689107860051564)),
 (3187, np.float64(0.567314930415771)),
 (885, np.float64(0.5670130066010409)),
 (1551, np.float64(0.5670130066010409)),
 (2809, np.float64(0.5670130066010409)),
 (434, np.float64(0.5661377159521145)),
 (679, np.float64(0.5661377159521145)),
 (807, np.float64(0.5661377159521145)),
 (1151, np.float64(0.5661377159521145)),
 (1672, np.float64(0.5661377159521145)),
 (2426, np.float64(0.5661377159521145)),
 (2523, np.float64(0.5661377159521145)),
 (2951, np.float64(0.5661377159521145)),
 (3690, np.float64(0.5661377159521145)),
 (3726, np.float64(0.5661377159521145)),
 (3264, np.float64(0.5642632966208664)),
 (2362, np.float64(0.5576311539908543)),
 (2350, np.float64(0.5567498871175283)),
 (3506, np.float64(0.5567498871175283)),
 (3509, np.float64(0.5567498871175283)),
 (3667, np.float64(0.5567498871175283)),
 (3668, np.float64(0.5567498871175283)),
 (160, np.float64(0.5551888381085528)),
 (330, np.float64(0.5551888381085528)),
 (339, np.float64(0.5551888381085528)),
 (399, np.float64(0.5551888381085528)),
 (614, np.float64(0.5551888381085528)),
 (708, np.float64(0.5551888381085528)),
 (717, np.float64(0.5551888381085528)),
 (776, np.float64(0.5551888381085528)),
 (777, np.float64(0.5551888381085528)),
 (1106, np.float64(0.5551888381085528)),
 (1290, np.float64(0.5551888381085528)),
 (1414, np.float64(0.5551888381085528)),
 (1420, np.float64(0.5551888381085528)),
 (1509, np.float64(0.5551888381085528)),
 (1726, np.float64(0.5551888381085528)),
 (1901, np.float64(0.5551888381085528)),
 (2000, np.float64(0.5551888381085528)),
 (2090, np.float64(0.5551888381085528)),
 (2170, np.float64(0.5551888381085528)),
 (2214, np.float64(0.5551888381085528)),
 (2498, np.float64(0.5551888381085528)),
 (3020, np.float64(0.5551888381085528)),
 (3605, np.float64(0.5535670949249368)),
 (2287, np.float64(0.5532443223092522)),
 (2446, np.float64(0.5532443223092522)),
 (2670, np.float64(0.5532443223092522)),
 (2709, np.float64(0.5532443223092522)),
 (3174, np.float64(0.550509079236272)),
 (3175, np.float64(0.550509079236272)),
 (3177, np.float64(0.550509079236272)),
 (2528, np.float64(0.5470715406109755)),
 (2919, np.float64(0.5470478050336657)),
 (2399, np.float64(0.5457710016732268)),
 (803, np.float64(0.5438828258207299)),
 (804, np.float64(0.5438828258207299)),
 (809, np.float64(0.5438828258207299)),
 (842, np.float64(0.5438828258207299)),
 (843, np.float64(0.5438828258207299)),
 (844, np.float64(0.5438828258207299)),
 (845, np.float64(0.5438828258207299)),
 (849, np.float64(0.5438828258207299)),
 (917, np.float64(0.5438828258207299)),
 (961, np.float64(0.5438828258207299)),
 (966, np.float64(0.5438828258207299)),
 (1136, np.float64(0.5438828258207299)),
 (1257, np.float64(0.5438828258207299)),
 (1283, np.float64(0.5438828258207299)),
 (1522, np.float64(0.5438828258207299)),
 (2729, np.float64(0.5438828258207299)),
 (2892, np.float64(0.5418384129548158)),
 (710, np.float64(0.5413315906049068)),
 (712, np.float64(0.5413315906049068)),
 (713, np.float64(0.5413315906049068)),
 (714, np.float64(0.5413315906049068)),
 (715, np.float64(0.5413315906049068)),
 (716, np.float64(0.5413315906049068)),
 (718, np.float64(0.5413315906049068)),
 (1019, np.float64(0.5413315906049068)),
 (1034, np.float64(0.5413315906049068)),
 (1557, np.float64(0.5413315906049068)),
 (2015, np.float64(0.5413315906049068)),
 (2111, np.float64(0.5413315906049068)),
 (2448, np.float64(0.5413315906049068)),
 (2591, np.float64(0.5413315906049068)),
 (2592, np.float64(0.5413315906049068)),
 (2600, np.float64(0.5413315906049068)),
 (2725, np.float64(0.5413315906049068)),
 (2750, np.float64(0.5413315906049068)),
 (2756, np.float64(0.5413315906049068)),
 (3172, np.float64(0.5413315906049068)),
 (1378, np.float64(0.5407933049019514)),
 (3263, np.float64(0.5401591010487814)),
 (2804, np.float64(0.5398899267788285)),
 (3331, np.float64(0.5397695791390273)),
 (3367, np.float64(0.5397695791390273)),
 (3386, np.float64(0.5397695791390273)),
 (3421, np.float64(0.5397695791390273)),
 (3450, np.float64(0.5397695791390273)),
 (3514, np.float64(0.5397695791390273)),
 (3567, np.float64(0.5397695791390273)),
 (3642, np.float64(0.5397695791390273)),
 (3708, np.float64(0.5397695791390273)),
 (1549, np.float64(0.5391154080834027)),
 (14, np.float64(0.5364532691242092)),
 (3154, np.float64(0.5357600449819124)),
 (474, np.float64(0.5315923790042426)),
 (629, np.float64(0.5315923790042426)),
 (672, np.float64(0.5315923790042426)),
 (1445, np.float64(0.5315923790042426)),
 (1658, np.float64(0.5315923790042426)),
 (2147, np.float64(0.5315923790042426)),
 (2506, np.float64(0.5315923790042426)),
 (3002, np.float64(0.5315923790042426)),
 (3003, np.float64(0.5315923790042426)),
 (3126, np.float64(0.5259841742451136)),
 (3321, np.float64(0.52588557391112)),
 (2549, np.float64(0.5246428441864709)),
 (1767, np.float64(0.5241941334207191)),
 (2752, np.float64(0.5241941334207191)),
 (2963, np.float64(0.5241941334207191)),
 (1447, np.float64(0.5237859535183959)),
 (2379, np.float64(0.5198703217308652)),
 (2417, np.float64(0.5198703217308652)),
 (3037, np.float64(0.5198703217308652)),
 (3612, np.float64(0.5198703217308652)),
 (2102, np.float64(0.5197997693752453)),
 (2683, np.float64(0.5197997693752453)),
 (2736, np.float64(0.5197997693752453)),
 (2795, np.float64(0.5197997693752453)),
 (2839, np.float64(0.5197997693752453)),
 (3006, np.float64(0.5197997693752453)),
 (1041, np.float64(0.5176637407705315)),
 (2930, np.float64(0.5166735952805896)),
 (2703, np.float64(0.5154299076098903)),
 (2917, np.float64(0.5150277990058629)),
 (1148, np.float64(0.5142228827320426)),
 (1001, np.float64(0.5135055507885423)),
 (1691, np.float64(0.5120160210292666)),
 (1755, np.float64(0.5120160210292666)),
 (2346, np.float64(0.5107431665102834)),
 (2649, np.float64(0.5107431665102834)),
 (2715, np.float64(0.5107431665102834)),
 (979, np.float64(0.5093652073188726)),
 (800, np.float64(0.5054252753442631)),
 (1401, np.float64(0.5012227646166757)),
 (1411, np.float64(0.5012227646166757)),
 (1439, np.float64(0.5012185425712564)),
 (1561, np.float64(0.5012185425712564)),
 (2934, np.float64(0.5008011414655356)),
 (1674, np.float64(0.4988667849367914)),
 (2699, np.float64(0.4988667849367914)),
 (3192, np.float64(0.49848517199553966)),
 (1547, np.float64(0.49431853852559626)),
 (2954, np.float64(0.4916270405640295)),
 (2972, np.float64(0.4916270405640295)),
 (3055, np.float64(0.4916270405640295)),
 (3127, np.float64(0.4916270405640295)),
 (3129, np.float64(0.4916270405640295)),
 (3141, np.float64(0.4916270405640295)),
 (3166, np.float64(0.4916270405640295)),
 (3206, np.float64(0.4916270405640295)),
 (3211, np.float64(0.4916270405640295)),
 (3234, np.float64(0.4916270405640295)),
 (3276, np.float64(0.4916270405640295)),
 (3288, np.float64(0.4916270405640295)),
 (3300, np.float64(0.4916270405640295)),
 (3305, np.float64(0.4916270405640295)),
 (3357, np.float64(0.4916270405640295)),
 (3422, np.float64(0.4916270405640295)),
 (3674, np.float64(0.4916270405640295)),
 (3717, np.float64(0.4916270405640295)),
 (1470, np.float64(0.49136881147386124)),
 (3069, np.float64(0.4903661845435687)),
 (452, np.float64(0.4899771719934112)),
 (461, np.float64(0.4899771719934112)),
 (1117, np.float64(0.4899771719934112)),
 (2732, np.float64(0.4899771719934112)),
 (12, np.float64(0.4870026795406652)),
 (884, np.float64(0.4870026795406652)),
 (1687, np.float64(0.4870026795406652)),
 (3250, np.float64(0.4870026795406652)),
 (725, np.float64(0.4852209040517184)),
 (3610, np.float64(0.4852209040517184)),
 (6, np.float64(0.48384392028455536)),
 (244, np.float64(0.48384392028455536)),
 (1449, np.float64(0.48332162226608394)),
 (1973, np.float64(0.482198747372702)),
 (26, np.float64(0.48058761312312)),
 (183, np.float64(0.48058761312312)),
 (651, np.float64(0.48058761312312)),
 (1317, np.float64(0.48058761312312)),
 (2255, np.float64(0.48058761312312)),
 (2284, np.float64(0.48058761312312)),
 (2309, np.float64(0.48058761312312)),
 (3183, np.float64(0.4805136331937885)),
 (1017, np.float64(0.478447815476489)),
 (2335, np.float64(0.4773484280896934)),
 (3252, np.float64(0.4770783287236135)),
 (2920, np.float64(0.4764249382972534)),
 (615, np.float64(0.4747176722830165)),
 (984, np.float64(0.4747176722830165)),
 (1230, np.float64(0.4747176722830165)),
 (1246, np.float64(0.4747176722830165)),
 (1437, np.float64(0.4747176722830165)),
 (1643, np.float64(0.4747176722830165)),
 (1729, np.float64(0.4747176722830165)),
 (1854, np.float64(0.4747176722830165)),
 (1856, np.float64(0.4747176722830165)),
 (2148, np.float64(0.4747176722830165)),
 (2464, np.float64(0.4747176722830165)),
 (2612, np.float64(0.4747176722830165)),
 (2700, np.float64(0.4747176722830165)),
 (305, np.float64(0.47303569687510205)),
 (1093, np.float64(0.47303569687510205)),
 (1521, np.float64(0.47303569687510205)),
 (1597, np.float64(0.47303569687510205)),
 (1877, np.float64(0.47303569687510205)),
 (1999, np.float64(0.47303569687510205)),
 (40, np.float64(0.4724859846988139)),
 (1689, np.float64(0.4724859846988139)),
 (2113, np.float64(0.4724859846988139)),
 (2369, np.float64(0.4724859846988139)),
 (52, np.float64(0.4722674995689695)),
 (406, np.float64(0.4722674995689695)),
 (1707, np.float64(0.4722674995689695)),
 (2388, np.float64(0.4722674995689695)),
 (2456, np.float64(0.4722674995689695)),
 (2519, np.float64(0.4722674995689695)),

In [55]:
for index, score in top_recommendations:
    print(df.iloc[index]["SongName"], score)

INDUSTRY BABY (feat. Jack Harlow) 0.847277327633418
Lucky You (feat. Joyner Lucas) 0.847277327633418
INDUSTRY BABY (feat. Jack Harlow) 0.847277327633418
Hall of Fame (feat. will.i.am) 0.847277327633418
STAY (with Justin Bieber) 0.847277327633418